#!/bin/bash

echo "📱 iPhone 壁纸生成器 - GitHub 设置指南"
echo "======================================"
echo ""
echo "请按以下步骤操作："
echo ""
echo "1. 打开浏览器，访问 GitHub 创建新仓库："
echo "   https://github.com/new"
echo ""
echo "2. 填写仓库信息："
echo "   Repository name: daily-wallpaper"
echo "   Description: iPhone壁纸生成器 - 让你的目标每天陪伴着你"
echo "   选择: Public"
echo "   ⚠️ 不要勾选任何初始化选项（README, .gitignore, license）"
echo ""
echo "3. 创建后，复制下面的命令（替换你的用户名）："
echo ""
echo "git remote add origin https://github.com/你的用户名/daily-wallpaper.git"
echo "git push -u origin main"
echo ""
echo "4. 启用 GitHub Pages:"
echo "   - 进入仓库 Settings → Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo "   - 点击 Save"
echo ""
echo "5. 等待几分钟后访问:"
echo "   https://你的用户名.github.io/daily-wallpaper/"
echo ""
echo "======================================"
echo "代码已经准备好了，就等你创建仓库了！"